function F_y = Force_y(y,theta,w1,w2,b,k,A,w,alpha)
%FORCE_Y
%    F_Y = FORCE_Y(Y,THETA,W1,W2,B,K,A,W,ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 5.9.
%    02-May-2013 21:12:10

t2 = sin(theta);
t3 = t2.*w;
t4 = A+t3-y;
t5 = 1.0./A;
t6 = t4.^2;
t7 = 1.0./pi;
t8 = A.^2;
t9 = -t6+t8;
t10 = 1.0./A.^2;
t11 = -t6.*t10+1.0;
t12 = 1.0./sqrt(t11);
t13 = 1.0./sqrt(t9);
t14 = A.*2.0;
t15 = t2.*w.*2.0;
t16 = t14+t15-y.*2.0;
F_y = real((k.*t7.*(w2+alpha.*w1).*(pi-acos(t4.*t5)-t13.*t16.*(1.0./2.0)+t4.*t5.*t12).*(-1.0./2.0))./w1-(b.*t7.*w1.*w2.*(w1-alpha.*w2).*(A.*t12+sqrt(t9)-t4.*t13.*t16.*(1.0./2.0)).*(1.0./2.0))./(w1+w2));
