function F_th = Force_th(y,theta,w1,w2,b,k,A,w,alpha)
%FORCE_TH
%    F_TH = FORCE_TH(Y,THETA,W1,W2,B,K,A,W,ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 5.9.
%    02-May-2013 21:12:11

t2 = cos(theta);
t3 = sin(theta);
t4 = t3.*w;
t5 = A+t4-y;
t6 = 1.0./A;
t7 = t5.^2;
t8 = 1.0./pi;
t9 = A.^2;
t10 = -t7+t9;
t11 = 1.0./A.^2;
t12 = -t7.*t11+1.0;
t13 = 1.0./sqrt(t12);
t14 = 1.0./sqrt(t10);
F_th = real((k.*t8.*(w2+alpha.*w1).*(t2.*w.*(pi-acos(t5.*t6))-t2.*t5.*t14.*w+t2.*t5.*t6.*t13.*w).*(1.0./2.0))./w1+(b.*t8.*w1.*w2.*(w1-alpha.*w2).*(t2.*sqrt(t10).*w-t2.*t7.*t14.*w+A.*t2.*t13.*w).*(1.0./2.0))./(w1+w2));
