function F_y = Force_y(y,theta,phi,w1,w2,b,k,A,l,w,alpha)
%FORCE_Y
%    F_Y = FORCE_Y(Y,THETA,PHI,W1,W2,B,K,A,L,W,ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 5.9.
%    01-May-2013 22:33:25

t2 = sin(theta);
t3 = sin(phi);
t4 = t3.*w;
t7 = l.*t2;
t5 = A+t4-t7-y;
t6 = 1.0./A;
t8 = t5.^2;
t9 = 1.0./pi;
t10 = A.^2;
t11 = -t8+t10;
t12 = 1.0./A.^2;
t13 = -t8.*t12+1.0;
t14 = 1.0./sqrt(t13);
t15 = 1.0./sqrt(t11);
t16 = A.*2.0;
t17 = t3.*w.*2.0;
t18 = t16+t17-y.*2.0-l.*t2.*2.0;
F_y = real((k.*t9.*(w2+alpha.*w1).*(pi-acos(t5.*t6)-t15.*t18.*(1.0./2.0)+t5.*t6.*t14).*(-1.0./2.0))./w1-(b.*t9.*w1.*w2.*(w1-alpha.*w2).*(A.*t14+sqrt(t11)-t5.*t15.*t18.*(1.0./2.0)).*(1.0./2.0))./(w1+w2));
