function F = Force(y,theta,phi,w1,w2,b,k,A,l,w,alpha)
%FORCE
%    F = FORCE(Y,THETA,PHI,W1,W2,B,K,A,L,W,ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 5.9.
%    01-May-2013 22:33:24

t3 = sin(theta);
t4 = l.*t3;
t5 = sin(phi);
t6 = t5.*w;
t2 = A-t4+t6-y;
t7 = 1.0./pi;
t8 = t2.^2;
t9 = A.^2;
t10 = -t8+t9;
t11 = sqrt(t10);
t12 = 1.0./A;
t13 = t2.*t12;
t14 = acos(t13);
t15 = pi-t14;
F = real((k.*t7.*(w2+alpha.*w1).*(t11+t2.*t15).*(1.0./2.0))./w1+(b.*t7.*w1.*w2.*(w1-alpha.*w2).*(t2.*t11+t9.*t15).*(1.0./2.0))./(w1+w2));
